baseURL = 'https://oliviasimonet.netlify.app/'
languageCode = 'en-us'
title = 'Olivia Simonet • Portfolio'
theme = "portfolio-v1"

summaryLength = 10

[menu]
  [[menu.main]]
    name = "Projets"
    pre = "pen-tool"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Contact"
    pre = "tag"
    url = "/contact/"
    weight = 2
  [[menu.main]]
    name = "À propos"
    pre = "tag"
    url = "/about/"
    weight = 3

[taxonomies]
  category = 'categories'
  technology = 'technologies'