baseURL = 'https://oliviasimonet.netlify.app/'
languageCode = 'en-us'
title = 'Olivia Simonet • Portfolio'
theme = "portfolio-v1"

summaryLength = 10

[menu]
  [[menu.main]]
    name = "Projets"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 1
  [[menu.legal]]
    name = "Mentions légales"
    url = "/mentions-legales/"
    weight = 1
  [[menu.legal]]
    name = "Plan du site"
    url = "/plan-du-site/"
    weight = 2

[taxonomies]
  category = 'categories'
  technology = 'technologies'